language: python
python:
  - "3.6"
install:
  - pip install codecov
  - pip install Flask
  - pip install pybtex
  - pip install flask_sqlalchemy
script:
  - coverage run hw_8/hw8test.py
after_success:
  - codecov